### ISSUE TITLE
1.0 & Debug Child Manifest has the wrong limb name declared for "DL_LSHOULDER"

### ISSUE THREAD

**Issue by Psi-Hate** [hylian-modding/zzconvert-Blender-Link-Templates#3]
"DL_LSHOULDER" should be "Limb.13", however in the child manifests it is instead a typo, being "Limb.14", which is a name that belongs to "DL_LFOREARM". This is cataclysmic and has unseen consequences.... because I sure has hell haven't seen any. Why does this seemingly not screw anything up? Wack.

**Comment by CrookedPoe** [comment]
Submit a PR with the fix and I'll merge it.
